# Matrices and Matrix Operations

This function introduces various ways to create
matrices and how to use them in TensorFlow

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

/home/hduser/anaconda3/envs/myenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/hduser/anaconda3/envs/myenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/hduser/anaconda3/envs/myenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/hduser/anaconda3/envs/myenv/lib/python3.7/s

Start a graph session

In [2]:
sess = tf.Session()

### Declaring matrices

Identity Matrix:

In [3]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2x3 random norm matrix:

In [5]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[ 0.77962846 -1.3043672   0.65441114]
 [ 0.01740197 -0.02479331 -0.93893296]]


2x3 constant matrix:

In [6]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


3x2 random uniform matrix:

In [7]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[0.6044594  0.8114672 ]
 [0.5985272  0.7167752 ]
 [0.8193351  0.13970971]]


Create matrix from np array:

In [8]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Matrix Operations

Matrix addition/subtraction:

In [9]:
print(sess.run(A+B))
print(sess.run(B-B))

[[3.4913425 6.1426477 4.4598823]
 [4.49669   4.3382077 4.7380342]]
[[0. 0. 0.]
 [0. 0. 0.]]


Matrix Multiplication:

In [10]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


Matrix Transpose:

In [11]:
print(sess.run(tf.transpose(C)))

[[0.9548845  0.33897877 0.46964633]
 [0.94919467 0.4433124  0.7596921 ]]


Matrix Determinant:

In [12]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


Matrix Inverse:

In [13]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


Cholesky Decomposition:

In [14]:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Eigenvalues and Eigenvectors:  We use `tf.self_adjoint_eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [15]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]


In [16]:
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("/home/hduser/tmp/variable_logs", sess.graph)